language: c

compiler:
  - clang
  - gcc

branches:
  only:
  - travis

install:
  - sudo apt-get install cweb-latex
  - sudo apt-get install texlive-fonts-extra

# build libmarpa and execute tests
script:
  - (make test)

sudo: false  # faster builds using containers

notifications:
  irc: "irc.libera.chat#marpa"
